name: Sample GitHub workflow
on: [workflow_dispatch, push]
jobs: 
  job1:
    runs-on: ubuntu-latest
    environment: sit
    env:
      CLIENT: ${{ vars.CLIENT }}
      AGE: ${{ secrets.AGE }}
    outputs:
      file-name: ${{ steps.step11.outputs.name }}

    steps:
      - name: name of the step
        id: step11
        run: echo "name=valueofname" >>$GITHUB_OUTPUT
      - name: name of the step
        run: echo "Name of the client ${{ env.CLIENT }}"
      - name: age step
        run: echo "Age of the client ${{ env.AGE }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: step name
        id: step21
        run: echo "STEP_ID=step21" >> $GITHUB_OUTPUT
      - name: step name
        run: echo "step id is ${{ steps.step21.outputs.STEP_ID }}"
      - name: step name output usage
        run: echo "output is ${{ needs.job1.outputs.file-name }}"
