name: Sample GitHub workflow
on: workflow_dispatch
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: name of the step
        run: echo "echo some commands"
      - name: name of the step
        run: echo"print some values"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: step name
        run: echo "print statement"
      - name: step name
        run: echo "print statement"
